name: fanta
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - xgboost
  - flask
  - flask-cors
  - pip
  - pip:
    - nfl_data_py